import type { Metadata } from "next"
import { Plus_Jakarta_Sans } from "next/font/google"
import "./globals.css"
import { Toaster } from "@/components/ui/sonner"
import { cn } from "@/lib/utils"

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(jakarta.className, "antialiased", "bg-[#1E0F22]", "dark")}
      >
        <div className="animate-fade-in fixed inset-0  z-[-50] min-h-screen bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-[#0F7B82] to-[#240C1E] bg-fixed " />
        <Toaster />
        {children}
      </body>
    </html>
  )
}
